### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Pmantou** [aralroca/chat-with-deno-and-preact#1]
Error report after operation

![微信截图_20200914154830](https://user-images.githubusercontent.com/50099057/93058296-c72cf000-f6a1-11ea-9d5a-b53a1d1fd4de.png)

Check file:///C:/Users/86135/Desktop/workSpace/deno/example/chat-with-deno-and-preact/server.ts
error: TS2322 [ERROR]: Type 'import("https://deno.land/std@0.68.0/io/bufio").BufReader' is not assignable to type 'import("https://deno.land/std@0.69.0/io/bufio").BufReader'.
  Types have separate declarations of a private property 'buf'.
        bufReader: req.r,
        ~~~~~~~~~
    at file:///C:/Users/86135/Desktop/workSpace/deno/example/chat-with-deno-and-preact/server.ts:21:9

    The expected type comes from property 'bufReader' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufReader: BufReader;
      ~~~~~~~~~
        at https://deno.land/std@0.69.0/ws/mod.ts:416:3

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.68.0/io/bufio").BufWriter' is not assignable to type 'import("https://deno.land/std@0.69.0/io/bufio").BufWriter'.
  Types have separate declarations of a private property 'writer'.
        bufWriter: req.w,
        ~~~~~~~~~
    at file:///C:/Users/86135/Desktop/workSpace/deno/example/chat-with-deno-and-preact/server.ts:22:9

    The expected type comes from property 'bufWriter' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufWriter: BufWriter;
      ~~~~~~~~~
        at https://deno.land/std@0.69.0/ws/mod.ts:415:3

Found 2 errors.

**Comment by Pmantou** [comment]
运行的命令是deno run --allow-net --allow-read server.ts

**Comment by aralroca** [comment]
Which Deno version do you have? This was implemented with `deno 1.0.0-rc1`. Probably needs an update! 👍  Thanks to report it

**Comment by Pmantou** [comment]
&nbsp;deno version is 1.3.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aral Roca Gomez"<notifications@github.com&gt;; 
发送时间: 2020年9月14日(星期一) 下午3:53
收件人: "aralroca/chat-with-deno-and-preact"<chat-with-deno-and-preact@noreply.github.com&gt;; 
抄送: "等等"<1402649723@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aralroca/chat-with-deno-and-preact] 运行 (#1)





 
Which Deno version do you have? This was implemented with deno 1.0.0-rc1. Probably needs an update! 👍  Thanks to report it

**Comment by checkwoodson** [comment]
maybe new Version Error
chat no use.
this is demo ban....
用不了啊~

**Comment by aralroca** [comment]
This demo is old (2 years ago), feel free to update it
